<script>
function js_thml(){
	let code = "";
	code += "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n";
	code += "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n";
	code += "<head>\n";
	code += "<!--[if gte mso 9]>\n";
	code += "<xml>\n";
	code += "  <o:OfficeDocumentSettings>\n";
	code += "\t<o:AllowPNG/>\n";
	code += "\t<o:PixelsPerInch>96</o:PixelsPerInch>\n";
	code += "  </o:OfficeDocumentSettings>\n";
	code += "</xml>\n";
	code += "<![endif]-->\n";
	code += "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n";
	code += "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
	code += "  <meta name=\"x-apple-disable-message-reformatting\">\n";
	code += "  <!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\n";
	code += "  <title></title>\n";
	code += "  \n";
	code += "\t<style type=\"text/css\">\n";
	code += "\t  table, td { color: #000000; } a { color: #0000ee; text-decoration: underline; }\n";
	code += "@media only screen and (min-width: 620px) {\n";
	code += "  .u-row {\n";
	code += "\twidth: 600px !important;\n";
	code += "  }\n";
	code += "  .u-row .u-col {\n";
	code += "\tvertical-align: top;\n";
	code += "  }\n";
	code += "\n";
	code += "  .u-row .u-col-100 {\n";
	code += "\twidth: 600px !important;\n";
	code += "  }\n";
	code += "\n";
	code += "}\n";
	code += "\n";
	code += "@media (max-width: 620px) {\n";
	code += "  .u-row-container {\n";
	code += "\tmax-width: 100% !important;\n";
	code += "\tpadding-left: 0px !important;\n";
	code += "\tpadding-right: 0px !important;\n";
	code += "  }\n";
	code += "  .u-row .u-col {\n";
	code += "\tmin-width: 320px !important;\n";
	code += "\tmax-width: 100% !important;\n";
	code += "\tdisplay: block !important;\n";
	code += "  }\n";
	code += "  .u-row {\n";
	code += "\twidth: calc(100% - 40px) !important;\n";
	code += "  }\n";
	code += "  .u-col {\n";
	code += "\twidth: 100% !important;\n";
	code += "  }\n";
	code += "  .u-col > div {\n";
	code += "\tmargin: 0 auto;\n";
	code += "  }\n";
	code += "}\n";
	code += "body {\n";
	code += "  margin: 0;\n";
	code += "  padding: 0;\n";
	code += "}\n";
	code += "\n";
	code += "table,\n";
	code += "tr,\n";
	code += "td {\n";
	code += "  vertical-align: top;\n";
	code += "  border-collapse: collapse;\n";
	code += "}\n";
	code += "\n";
	code += ".ie-container table,\n";
	code += ".mso-container table {\n";
	code += "  table-layout: fixed;\n";
	code += "}\n";
	code += "\n";
	code += "* {\n";
	code += "  line-height: inherit;\n";
	code += "}\n";
	code += "\n";
	code += "a[x-apple-data-detectors='true'] {\n";
	code += "  color: inherit !important;\n";
	code += "  text-decoration: none !important;\n";
	code += "}\n";
	code += "\n";
	code += "</style>\n";
	code += "  \n";
	code += "  \n";
	code += "\n";
	code += "</head>\n";
	code += "\n";
	code += "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #dde9e4;color: #000000\">\n";
	code += "  <!--[if IE]><div class=\"ie-container\"><![endif]-->\n";
	code += "  <!--[if mso]><div class=\"mso-container\"><![endif]-->\n";
	code += "  <table style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #dde9e4;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\n";
	code += "  <tbody>\n";
	code += "  <tr style=\"vertical-align: top\">\n";
	code += "\t<td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n";
	code += "\t<!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #dde9e4;\"><![endif]-->\n";
	code += "\t\n";
	code += "\n";
	code += "<div class=\"u-row-container\" style=\"padding: 0px;background-color: #ffffff\">\n";
	code += "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\n";
	code += "\t<div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n";
	code += "\t  <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: #ffffff;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\n";
	code += "\t  \n";
	code += "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n";
	code += "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n";
	code += "  <div style=\"width: 100% !important;\">\n";
	code += "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n";
	code += "  \n";
	code += "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n";
	code += "  <tbody>\n";
	code += "\t<tr>\n";
	code += "\t  <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n";
	code += "\t\t\n";
	code += "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n";
	code += "  <tr>\n";
	code += "\t<td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n";
	code += "\t  <a href=\"https://unlayer.com/\" target=\"_blank\">\n";
	code += "\t  <img align=\"center\" border=\"0\" src=\"images/image-1.jpeg\" alt=\"Logo\" title=\"Logo\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 154px;\" width=\"154\"/>\n";
	code += "\t  </a>\n";
	code += "\t</td>\n";
	code += "  </tr>\n";
	code += "</table>\n";
	code += "\n";
	code += "\t  </td>\n";
	code += "\t</tr>\n";
	code += "  </tbody>\n";
	code += "</table>\n";
	code += "\n";
	code += "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n";
	code += "  </div>\n";
	code += "</div>\n";
	code += "<!--[if (mso)|(IE)]></td><![endif]-->\n";
	code += "\t  <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n";
	code += "\t</div>\n";
	code += "  </div>\n";
	code += "</div>\n";
	code += "\n";
	code += "\n";
	code += "\n";
	code += "<div class=\"u-row-container\" style=\"padding: 25px 0px 0px;background-color: #355d4c\">\n";
	code += "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\n";
	code += "\t<div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n";
	code += "\t  <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 25px 0px 0px;background-color: #355d4c;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\n";
	code += "\t  \n";
	code += "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n";
	code += "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n";
	code += "  <div style=\"width: 100% !important;\">\n";
	code += "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n";
	code += "  \n";
	code += "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n";
	code += "  <tbody>\n";
	code += "\t<tr>\n";
	code += "\t  <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n";
	code += "\t\t\n";
	code += "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n";
	code += "  <tr>\n";
	code += "\t<td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n";
	code += "\t  <a href=\"https://unlayer.com/\" target=\"_blank\">\n";
	code += "\t  <img align=\"center\" border=\"0\" src=\"images/image-2.jpeg\" alt=\"Hero Image\" title=\"Hero Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 600px;\" width=\"600\"/>\n";
	code += "\t  </a>\n";
	code += "\t</td>\n";
	code += "  </tr>\n";
	code += "</table>\n";
	code += "\n";
	code += "\t  </td>\n";
	code += "\t</tr>\n";
	code += "  </tbody>\n";
	code += "</table>\n";
	code += "\n";
	code += "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n";
	code += "  </div>\n";
	code += "</div>\n";
	code += "<!--[if (mso)|(IE)]></td><![endif]-->\n";
	code += "\t  <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n";
	code += "\t</div>\n";
	code += "  </div>\n";
	code += "</div>\n";
	code += "\n";
	code += "\n";
	code += "\n";
	code += "<div class=\"u-row-container\" style=\"padding: 0px 0px 25px;background-color: #355d4c\">\n";
	code += "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #264739;\">\n";
	code += "\t<div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n";
	code += "\t  <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px 0px 25px;background-color: #355d4c;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #264739;\"><![endif]-->\n";
	code += "\t  \n";
	code += "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n";
	code += "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n";
	code += "  <div style=\"width: 100% !important;\">\n";
	code += "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n";
	code += "  \n";
	code += "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n";
	code += "  <tbody>\n";
	code += "\t<tr>\n";
	code += "\t  <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n";
	code += "\t\t\n";
	code += "  <h1 style=\"margin: 0px; color: #fffefe; line-height: 140%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: comic sans ms,sans-serif; font-size: 22px;\">\n";
	code += "\t<strong>There are available court :<br /><br /><br /><br /><br /><br /><br /></strong>\n";
	code += "  </h1>\n";
	code += "\n";
	code += "\t  </td>\n";
	code += "\t</tr>\n";
	code += "  </tbody>\n";
	code += "</table>\n";
	code += "\n";
	code += "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n";
	code += "  </div>\n";
	code += "</div>\n";
	code += "<!--[if (mso)|(IE)]></td><![endif]-->\n";
	code += "\t  <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n";
	code += "\t</div>\n";
	code += "  </div>\n";
	code += "</div>\n";
	code += "\n";
	code += "\n";
	code += "\n";
	code += "<div class=\"u-row-container\" style=\"padding: 0px;background-color: #1c3b2f\">\n";
	code += "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\n";
	code += "\t<div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n";
	code += "\t  <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: #1c3b2f;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\n";
	code += "\t  \n";
	code += "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n";
	code += "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n";
	code += "  <div style=\"width: 100% !important;\">\n";
	code += "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n";
	code += "  \n";
	code += "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n";
	code += "  </div>\n";
	code += "</div>\n";
	code += "<!--[if (mso)|(IE)]></td><![endif]-->\n";
	code += "\t  <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n";
	code += "\t</div>\n";
	code += "  </div>\n";
	code += "</div>\n";
	code += "\n";
	code += "\n";
	code += "\t<!--[if (mso)|(IE)]></td></tr></table><![endif]-->\n";
	code += "\t</td>\n";
	code += "  </tr>\n";
	code += "  </tbody>\n";
	code += "  </table>\n";
	code += "  <!--[if mso]></div><![endif]-->\n";
	code += "  <!--[if IE]></div><![endif]-->\n";
	code += "</body>\n";
	code += "\n";
	code += "</html>\n";
	code += "\n";
	return code;
}


document.getElementById("js_html").innerText = js_thml();
document.getElementById("html-text").value = js_thml();
</script>